### ISSUE TITLE
Add port configuration

### ISSUE THREAD

**Issue by fmusayev** [crhistianramirez/jiraIssues#2]
Hi, 
I ran into a problem while connecting to the jira api, I assume that this may be due to the port number, my port number is 8443 (baseUrl: "https://jira.****.local:8443"), but it shows additional port 443

<img width="484" alt="jira-issues-error" src="https://user-images.githubusercontent.com/46884462/56468663-66639e80-6440-11e9-8947-41ab92fb3565.png">

It would be nice if port number can be configurable also
can you please help me with this problem?

**Comment by fmusayev** [comment]
I fixed the issue for now by adding hardcoded
`port: "8443"`
in jiraFactory.js

**Comment by crhistianramirez** [comment]
fixed w pull request: https://github.com/crhistianramirez/jiraIssues/pull/3
new version avialable here: https://marketplace.visualstudio.com/items?itemName=crhistianr.jira-issues

I biffed the semantic versioning 🤦‍♂️
