### ISSUE TITLE
issue: Error "Not able to sort using field Rank

### ISSUE THREAD

**Issue by magneticcore** [crhistianramirez/jiraIssues#6]
In Explorer, Jira issues displays the following error:
Error code: 400
Error message: Not able to sort using field Rank

Jira: v7.4.5

### Update;
At startup of vs code, Jira Issues calls jira.baseUrl/rest/api/2/search that returns a json file: search.json. This file doesn't contains any Rank information

**Comment by crhistianramirez** [comment]
What does your jql expression look like? And if you use that same expression in [Jira's advanced search](https://confluence.atlassian.com/jirasoftwarecloud/advanced-searching-764478330.html) does it work?

**Comment by magneticcore** [comment]
I didn't change anything about jql expression, I just installed your plugin and gives the necessary settings jira.baseUrl, jira.username, jira.password, jira.port ("").After I restarted VS code and in the explorer, the error raised directly

**Comment by crhistianramirez** [comment]
The default JQL expression I have in there if none is provided looks like this
> assignee = currentUser() AND resolution = EMPTY ORDER BY Rank ASC

Looks like I was making too many assumptions and ordering by rank only works [if enabled first](https://confluence.atlassian.com/jirasoftwarecloud/enabling-ranking-764477994.html). In light of this I'll update the default expression to exclude ordering by rank. 

@magneticcore  Thank you very much for bringing this to my attention.

**Comment by crhistianramirez** [comment]
fixed and released under version 1.2.1
